[[entry]]
timestamp = 1735862400
appid = "2982750"
title = "The Violets of Amicus™ Demo"
[[entry]]
timestamp = 1735862400
appid = "3406500"
title = "SOG: Vietnam Demo"
[[entry]]
timestamp = 1736121600
appid = "3354780"
title = "The Scouring Demo"
[[entry]]
timestamp = 1736121600
appid = "3366180"
title = "Rogue Loops Demo"
[[entry]]
timestamp = 1736294400
appid = "3264080"
title = "Hidden Cat Outlaws Demo"
[[entry]]
timestamp = 1736294400
appid = "3388650"
title = "Locator Demo"
[[entry]]
timestamp = 1736294400
appid = "3413460"
title = "GameStonk Simulator Demo"
[[entry]]
timestamp = 1736294400
appid = "3418550"
title = "Forklift Certified Demo"
[[entry]]
timestamp = 1736294400
appid = "3418590"
title = "Fair and Square Demo"
[[entry]]
timestamp = 1736812800
appid = "2741670"
title = "MINDWAVE Demo"
[[entry]]
timestamp = 1736812800
appid = "3051010"
title = "Bonnie Bear Saves Frogtime Demo"
[[entry]]
timestamp = 1736899200
appid = "3420970"
title = "Inkwellers Demo"
[[entry]]
timestamp = 1736985600
appid = "3351700"
title = "The First Berserker: Khazan Demo"
[[entry]]
timestamp = 1736985600
appid = "3442630"
title = "BOKURA: planet Special Demo"
[[entry]]
timestamp = 1737072000
appid = "3400850"
title = "Calyx Demo"
[[entry]]
timestamp = 1737331200
appid = "2964010"
title = "Private Military Manager: Tactical Auto Battler Demo"
[[entry]]
timestamp = 1737331200
appid = "3307570"
title = "Crown of Greed Demo"
[[entry]]
timestamp = 1737331200
appid = "3328600"
title = "Coin Push RPG Demo"
[[entry]]
timestamp = 1737331200
appid = "3364820"
title = "Project Chameleon Demo"
[[entry]]
timestamp = 1737331200
appid = "3365740"
title = "Death Howl Demo"
[[entry]]
timestamp = 1737331200
appid = "3391250"
title = "Echoes of the Architects Demo"
[[entry]]
timestamp = 1737417600
appid = "3212360"
title = "永生之庭 Demo"
[[entry]]
timestamp = 1737504000
appid = "3395240"
title = "Disastory Demo"
[[entry]]
timestamp = 1737504000
appid = "3435860"
title = "Roots Devour Demo"
[[entry]]
timestamp = 1737590400
appid = "3456690"
title = "Just A Shadow Game Demo"
[[entry]]
timestamp = 1737676800
appid = "3464460"
title = "Escape From Duckov Demo"
[[entry]]
timestamp = 1737936000
appid = "3440020"
title = "VOIDFACE Demo"
[[entry]]
timestamp = 1738022400
appid = "3465430"
title = "Desktop Fishing Demo"
[[entry]]
timestamp = 1738195200
appid = "3376980"
title = "Anoxia Station Demo"
[[entry]]
timestamp = 1738195200
appid = "3437260"
title = "HR Simulator Demo"
[[entry]]
timestamp = 1738281600
appid = "3237900"
title = "香恋Ready！ Demo"
[[entry]]
timestamp = 1738281600
appid = "3457300"
title = "Guilty as Sock! Demo"
[[entry]]
timestamp = 1738281600
appid = "3458150"
title = "Lyca Demo"
[[entry]]
timestamp = 1738281600
appid = "3460550"
title = "Firefighters Together Demo"
[[entry]]
timestamp = 1738281600
appid = "3479320"
title = "Farming & Supermarket Simulator Demo"
[[entry]]
timestamp = 1738281600
appid = "3490390"
title = "Sandustry Demo"
[[entry]]
timestamp = 1738281600
appid = "3495010"
title = "MIKU: May I Keep Up? Demo"
[[entry]]
timestamp = 1738281600
appid = "3497550"
title = "Hamster Hunter: Rodent Rampage Demo"
[[entry]]
timestamp = 1738368000
appid = "3450720"
title = "森林粉碎者 Demo"
[[entry]]
timestamp = 1738454400
appid = "3461030"
title = "Soggy Beans Demo"
[[entry]]
timestamp = 1738454400
appid = "3476760"
title = "Dotu Demo"
[[entry]]
timestamp = 1738540800
appid = "3405610"
title = "Berserk B.I.T.S Demo"
[[entry]]
timestamp = 1738540800
appid = "3475100"
title = "Void War Demo"
[[entry]]
timestamp = 1738540800
appid = "3487310"
title = "Bongo Cat Demo"
[[entry]]
timestamp = 1738540800
appid = "3488310"
title = "Nomad Idle Demo"
[[entry]]
timestamp = 1738627200
appid = "3408620"
title = "Cafemart Simulator Demo"
[[entry]]
timestamp = 1738627200
appid = "3468320"
title = "Do No Harm Demo"
[[entry]]
timestamp = 1738627200
appid = "3469520"
title = "Iron Convoy Demo"
[[entry]]
timestamp = 1738627200
appid = "3489890"
title = "Desktop Cat Cafe Demo"
[[entry]]
timestamp = 1738713600
appid = "2738220"
title = "Dino Path Trail Demo"
[[entry]]
timestamp = 1738713600
appid = "3484140"
title = "东方异域见闻 ~ Touhou Dystopian Demo"
[[entry]]
timestamp = 1738800000
appid = "3367510"
title = "Tackle for Loss Demo"
[[entry]]
timestamp = 1738800000
appid = "3401180"
title = "Blobun Demo"
[[entry]]
timestamp = 1738800000
appid = "3492540"
title = "Upstream Demo"
[[entry]]
timestamp = 1738800000
appid = "3497430"
title = "Freddy Farmer Demo"
[[entry]]
timestamp = 1738886400
appid = "3354060"
title = "ELISSA ：Body in the bedroom Demo"
[[entry]]
timestamp = 1738886400
appid = "3374350"
title = "Bad Cheese Demo"
[[entry]]
timestamp = 1738886400
appid = "3403460"
title = "Mech Havoc: The Destructive Demo"
[[entry]]
timestamp = 1738886400
appid = "3426800"
title = "Delverium Demo"
[[entry]]
timestamp = 1738886400
appid = "3463790"
title = "Hypogea Demo"
[[entry]]
timestamp = 1738886400
appid = "3491930"
title = "Noobs Are Coming DEMO"
[[entry]]
timestamp = 1738972800
appid = "3512220"
title = "Metal Hunter Demo"
[[entry]]
timestamp = 1739059200
appid = "3481790"
title = "LOVE SHOP Simulator 💕🛒 Demo"
[[entry]]
timestamp = 1739145600
appid = "3073400"
title = "Seagulls - Crappy Situation Demo"
[[entry]]
timestamp = 1739145600
appid = "3222620"
title = "Nightmare Shift Demo"
[[entry]]
timestamp = 1739145600
appid = "3375100"
title = "DuneCrawl Demo"
[[entry]]
timestamp = 1739145600
appid = "3399490"
title = "Touhou: the Unreachable Oneiroborder. Demo"
[[entry]]
timestamp = 1739145600
appid = "3403600"
title = "RailGods of Hysterra Demo"
[[entry]]
timestamp = 1739145600
appid = "3413250"
title = "Desperate Place Demo"
[[entry]]
timestamp = 1739145600
appid = "3450210"
title = "Sheepherds! Demo"
[[entry]]
timestamp = 1739145600
appid = "3451510"
title = "Roombattle Demo"
[[entry]]
timestamp = 1739145600
appid = "3453220"
title = "Biped 2 Demo"
[[entry]]
timestamp = 1739145600
appid = "3453320"
title = "Squirreled Away Demo"
[[entry]]
timestamp = 1739145600
appid = "3462260"
title = "Aethermancer Demo"
[[entry]]
timestamp = 1739145600
appid = "3466550"
title = "Gemporium Demo"
[[entry]]
timestamp = 1739145600
appid = "3509220"
title = "Neon Inferno Demo"
[[entry]]
timestamp = 1739145600
appid = "3510080"
title = "Kentum Demo"
[[entry]]
timestamp = 1739232000
appid = "2582150"
title = "Ruffy and the Riverside Demo"
[[entry]]
timestamp = 1739232000
appid = "3138110"
title = "Lost in Prayer Demo"
[[entry]]
timestamp = 1739318400
appid = "2506090"
title = "Twisted Tower Demo"
[[entry]]
timestamp = 1739318400
appid = "3186700"
title = "Double Whammy Demo"
[[entry]]
timestamp = 1739318400
appid = "3415070"
title = "Greenhouse Demo"
[[entry]]
timestamp = 1739318400
appid = "3476570"
title = "東方幕華祭 永夜篇 Demo Touhou Makuka Sai ~ Fantastic Danmaku Festival Part III Demo"
[[entry]]
timestamp = 1739318400
appid = "3478820"
title = "Wordatro! Demo"
[[entry]]
timestamp = 1739318400
appid = "3479130"
title = "Sex & Coffee ☕️🤎 Demo"
[[entry]]
timestamp = 1739404800
appid = "3352550"
title = "Like a Dragon: Pirate Yakuza in Hawaii Demo"
[[entry]]
timestamp = 1739404800
appid = "3380460"
title = "GearGrit Demo"
[[entry]]
timestamp = 1739404800
appid = "3381200"
title = "Lost in Random: The Eternal Die Demo"
[[entry]]
timestamp = 1739404800
appid = "3402770"
title = "Badlands Crew Demo"
[[entry]]
timestamp = 1739404800
appid = "3429540"
title = "Piece by Piece Demo"
[[entry]]
timestamp = 1739404800
appid = "3453690"
title = "Supercar Collection Simulator Demo"
[[entry]]
timestamp = 1739404800
appid = "3462550"
title = "Locomoto Demo"
[[entry]]
timestamp = 1739404800
appid = "3469870"
title = "Deepspace Emporium Demo"
[[entry]]
timestamp = 1739404800
appid = "3498810"
title = "Knightica Demo"
[[entry]]
timestamp = 1739404800
appid = "3499130"
title = "Lou's Lagoon Demo"
[[entry]]
timestamp = 1739491200
appid = "3280910"
title = "Haneda Girl Demo"
[[entry]]
timestamp = 1739491200
appid = "3428250"
title = "恋爱绮谭 不存在的回忆 Demo"
[[entry]]
timestamp = 1739491200
appid = "3447260"
title = "House of Necrosis Demo"
[[entry]]
timestamp = 1739491200
appid = "3453620"
title = "Hoover Heroes Demo"
[[entry]]
timestamp = 1739491200
appid = "3490200"
title = "LOVE Hotel Simulator 🏩 Demo"
[[entry]]
timestamp = 1739664000
appid = "3509810"
title = "Blueprint Bob Demo"
[[entry]]
timestamp = 1739750400
appid = "3382420"
title = "PSYCHExFUSE Demo"
[[entry]]
timestamp = 1739750400
appid = "3396390"
title = "Fourth Time Around Demo"
[[entry]]
timestamp = 1739750400
appid = "3408840"
title = "ChromaGun 2: Dye Hard Demo"
[[entry]]
timestamp = 1739836800
appid = "3386470"
title = "The Hundred Line -Last Defense Academy- Demo Ver."
[[entry]]
timestamp = 1739836800
appid = "3522510"
title = "Laundry Simulator : PowerWash It! Demo"
[[entry]]
timestamp = 1739836800
appid = "3525590"
title = "Chaos Front Demo"
[[entry]]
timestamp = 1739923200
appid = "2778240"
title = "Moves Of The Diamond Hand Demo"
[[entry]]
timestamp = 1739923200
appid = "2852420"
title = "Beholder: Conductor Demo"
[[entry]]
timestamp = 1739923200
appid = "3539780"
title = "What Comes Next Demo"
[[entry]]
timestamp = 1740009600
appid = "2870990"
title = "Mecha BREAK Demo"
[[entry]]
timestamp = 1740009600
appid = "2958050"
title = "Machine Mind Demo"
[[entry]]
timestamp = 1740009600
appid = "2958740"
title = "Luctus Demo"
[[entry]]
timestamp = 1740009600
appid = "3152580"
title = "Amarillo's Desktop Pets Demo"
[[entry]]
timestamp = 1740009600
appid = "3227160"
title = "SAVE Demo"
[[entry]]
timestamp = 1740009600
appid = "3398800"
title = "Sex Wishes 🔮 Demo"
[[entry]]
timestamp = 1740009600
appid = "3449000"
title = "Hoop Fighters Demo"
[[entry]]
timestamp = 1740009600
appid = "3453980"
title = "Nordhold Demo"
[[entry]]
timestamp = 1740009600
appid = "3456560"
title = "Cubic Odyssey Demo"
[[entry]]
timestamp = 1740009600
appid = "3457160"
title = "Radiolight Demo"
[[entry]]
timestamp = 1740009600
appid = "3463280"
title = "Motorcycle Night Ride Demo"
[[entry]]
timestamp = 1740009600
appid = "3491390"
title = "Static Dread Demo"
[[entry]]
timestamp = 1740096000
appid = "2966870"
title = "Shotgun Cop Man Demo"
[[entry]]
timestamp = 1740096000
appid = "3361040"
title = "Lost Skies Demo"
[[entry]]
timestamp = 1740096000
appid = "3493310"
title = "Chains of Freedom Demo"
